### PR TITLE
Adding microphone and wirelessStatus widgets

### PR DESCRIPTION
**Pull request by bzgec**
New pull request with squashed commits for microphone and wirelessStatus widgets as requested

### CODE REVIEW

**Comment by lcpz** [comment]
Hi, sorry for the late reply.

The microphone widget seems very simple, can you please check if you can implement it as a [watcher](https://awesomewm.org/recipes/watch/)? It would be more maintainable.

Moreover, please add it to the `contrib/` folder and, if you like, add your signature in the copyright.

**Comment by bzgec** [comment]
In `theme.lua` file you could now use microphone widget like this:
```lua
-- Microphone
theme.mic = lain.widget.mic({
    settings = function()
        if theme.mic.state == "muted" then
            theme.mic.widget_imageBox:set_image(theme.widget_micMuted)
        else
            theme.mic.widget_imageBox:set_image(theme.widget_micUnmuted)
        end
    end
})
local widget_mic = wibox.widget { theme.mic.widget_imageBox, layout = wibox.layout.align.horizontal }
```

**Comment by lcpz** [comment]
What I am asking is if it is possible to create the widget by using `awful.widget.watch`, of which you can find examples [here](https://awesomewm.org/recipes/watch/). The reason is that relying on `awful` instead of `lain` would make your widget more durable. I will check it myself ASAP.

**Comment by bzgec** [comment]
Yes, I think I did that, it is in that commit above. Here is the new code:

```lua
--[[

     Licensed under GNU General Public License v2
      * (c) 2013,      Luca CPZ
      * (c) 2010-2012, Peter Hofmann

--]]

local helpers  = require("lain.helpers")
local wibox    = require("wibox")
local naughty  = require("naughty")
local awful    = require("awful")
local gears    = require("gears")

-- Microphone state
-- lain.widget.mic

local function factory(args)
    local args     = args or {}

    local timeout  = args.timeout or 10
    local settings = args.settings or function() end
    local mic      = {
        widget_imageBox = wibox.widget.imagebox(),
        timer = gears.timer,
        state = "unmute",
    }

    function mic.pressed(button)
        if button == 1 then
            helpers.async("amixer set Capture toggle")
            mic.update()
        end
    end

    function mic.update()
        mic.timer:emit_signal("timeout")
    end

    -- Read `amixer get Capture` command and try to `grep` all "[on]" lines.
    --   - If there are lines with "[on]" then assume microphone is "unmuted".
    --   - If there are NO lines with "[on]" then assume microphone is "muted".
    mic, mic.timer = awful.widget.watch(
        "bash -c \"amixer get Capture | grep '\\[on\\]'\"",
        timeout,
        function(widget, stdout, stderr, exitreason, exitcode)
            local current_micState = "error"

            if exitcode == 1 then
                -- Exit code 1 - no line selected
                current_micState = "muted"
            elseif exitcode == 0 then
                -- Exit code 0 - a line is selected
                current_micState = "unmuted"
            else
                -- Other exit code (2) - error occurred
                current_micState = "error"
            end

            -- Compare new and old state
            if current_micState ~= widget.state then
                if current_micState == "muted" then
                    naughty.notify({preset=naughty.config.presets.normal, title="mic widget info", text='muted'})
                elseif current_micState == "unmuted" then
                    naughty.notify({preset=naughty.config.presets.normal, title="mic widget info", text='unmuted'})
                else
                    naughty.notify({preset=naughty.config.presets.critical, title="mic widget error", text='Error on "amixer get Capture | grep \'\\[on\\]\'"'})
                end

                -- Store new microphone state
                widget.state = current_micState
            end

            -- Call user/theme defined function
            settings()
        end,
        mic
    )

    mic.widget_imageBox:connect_signal("button::press", function(c, _, _, button)
        mic.pressed(button)
    end)

    return mic
end

return factory

```

**Comment by lcpz** [comment]
Apologies, I did not check the latest commit.

Given that both can be implemented as watchers, there is no need to add them to `lain`.

Please open a pull request in [`awesome-www`](https://github.com/awesomeWM/awesome-www) and add them as [recipes](https://github.com/awesomeWM/awesome-www/tree/master/recipes).

**Comment by bzgec** [comment]
I see your point. I can add it to [awesome-www](https://github.com/awesomeWM/awesome-www). Do you plan to move all the `lain` widgets to awesome-www?

**Comment by lcpz** [comment]
> Do you plan to move all the lain widgets to awesome-www?

Only those so simple that they can be re-implemented as watchers.

I see that both your proposed widgets can be implemented as watchers (I did something similar to `wirelessStatus` [here](https://github.com/lcpz/awesome-copycats/blob/master/themes/vertex/theme.lua#L233)).

Hence, unless you want to develop more complex widgets, please close this PR and submit to the Awesome website repository.

**Comment by bzgec** [comment]
Yes I think i took [that](https://github.com/lcpz/awesome-copycats/blob/master/themes/vertex/theme.lua#L233) as a starting point for `wirelessStatus`.

Ok closing the pull request.

**Pull request closed without merging**
