### PR TITLE
Made paths relative

### PR DESCRIPTION
**Pull request by thomascft**

### CODE REVIEW

**Comment by thomascft** [comment]
It appears there is already another open request accomplishing similar things. If that's still being considered I can close this, if not I have tested everything, and as far as I can tell it works.

**Comment by lcpz** [comment]
Yes, already considered in #525.

Did you do your tests manually? Could you help with #527 so to make them automated?

**Comment by thomascft** [comment]
I don't have to a of experience, but I'd be willing to help.

**Comment by thomascft** [comment]
Well, I don't know git well enough clearly. I setup the testing, you can see the output [here](https://github.com/thomascft/lain/runs/6803123961?check_suite_focus=true). I had a bit of cleanup, so that's what the force pushes were, oh... I'm gonna close the pull request and do it with in reference of #527

**Pull request closed without merging**
